baseurl: "/"
languageCode: "en-us"
title: 'HumLUG - Humboldt Linux Users Group'
theme: "hugo-minimal"
footnotereturnlinkcontents: "â†©"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: "about/"
      weight: 2
    - name: Annoucements
      url: "announcements/"
      weight: 3
    - name: Events
      url: "events/"
      weight: 4
    - name: Join
      url: "join/"

params:
  description: "Official website of the Humboldt Linux Users Group (HumLUG)."
  footer: "All logos and trademarks in this site are property of their respective owner. Anything else not covered by it's own copyright is &copy; 2022 -- {Year} humlug.org -- [Github repo](https://github.com/samuelmcpherson/humlug.github.io) -- Contact the site [admin](mailto:contact@samuelmcpherson.net)"
